on:
  push:
    branches:
      - main
      - crane-tag
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      # - run: nix build .#test --impure
      - run: nix run .#testDockerManifest --impure -L
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'mirkolenz' && github.event_name == 'push' }}
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: cihelper/action-semanticrelease-generic@v1
